<!doctype html>
<html class="no-js" lang="pt_BR" ng-app="zup-app">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
       
        <!-- Bootstrap -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <!-- Font Awesome -->
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

        <link rel="stylesheet" href="<?= SITE_URL; ?>/css/main.css">
    </head>
    <body>
       	<div class="navbar navbar-inverse navbar-fixed-left">
			<a class="navbar-brand" href="#">Zup</a>
			<ul class="nav navbar-nav">
				<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Modelos <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li><a href="<?= SITE_URL; ?>/modelos">Todos</a></li>
						<li><a href="<?= SITE_URL; ?>/novo">Novo</a></li>
					</ul>
				</li>
			</ul>
		</div>
		<div class="container">
            <?php include htmlspecialchars($slug).".phtml"; ?>		
		</div>
        
        <!-- jQuery -->
        <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
        <!-- Bootstrap -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <!-- AngularJS -->
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.4/angular.min.js"></script>
        <script type="text/javascript" src="https://code.angularjs.org/1.4.4/i18n/angular-locale_pt-br.js"></script>
        <script type="text/javascript" src="<?= SITE_URL; ?>/js/zup.app.js"></script>
        <script type="text/javascript" src="<?= SITE_URL; ?>/js/zup.factory.js"></script>
        <script type="text/javascript" src="<?= SITE_URL; ?>/js/zup.controller.js"></script>

        <script type="text/javascript" src="<?= SITE_URL; ?>/js/main.js"></script>
    </body>
</html>